version: "3"

volumes:
  caddy_data:
  caddy_config:
  caddy_logs:
  loki_data:
  grafana_data:

networks:
  logging:
    name: logging

services:
  website:
    container_name: website
    build: ./frontend
    restart: unless-stopped
    ports:
      - "8080:3000"
    networks:
      - logging
    logging:
      driver: "loki"
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"

  swatch:
    container_name: swatch
    image: vocksel/swatch:main
    restart: unless-stopped
    ports:
      - "8100:8080"
    networks:
      - logging
    logging:
      driver: "loki"
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"

  caddy:
    container_name: caddy
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    networks:
      - logging
    logging:
      driver: "loki"
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"

  loki:
    container_name: loki
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yml:/etc/loki-config.yml
      - loki_data:/loki
    command: -config.file=/etc/loki-config.yml
    networks:
      - logging

  promtail:
    container_name: promtail
    image: grafana/promtail:2.9.4
    volumes:
      - ./promtail.yml:/etc/promtail/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_logs:/var/log/caddy:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - logging

  grafana:
    container_name: grafana
    image: grafana/grafana:10.3.1
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - logging
